# Generated by Django 5.2.16 on 2026-07-24 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_key', models.CharField(db_index=True, max_length=9, unique=True)),
                ('is_private', models.BooleanField(default=True)),
                ('invite_code', models.CharField(db_index=True, max_length=12)),
                ('max_members', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Pickem Group',
                'verbose_name_plural': 'Pickem Groups',
                'db_table': 'pickem_groups',
            },
        ),
        migrations.CreateModel(
            name='GamePickem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=10)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickems', to='scheduling.game')),
            ],
            options={
                'verbose_name': 'Game Pickem',
                'verbose_name_plural': 'Game Pickems',
                'db_table': 'game_pickems',
                'ordering': ['-game__week__season__year', '-game__week__week', 'game__game_time'],
            },
        ),
        migrations.CreateModel(
            name='PickemGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Member', 'Member')], default='Member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pickems.pickemgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickem_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pickem Group Member',
                'verbose_name_plural': 'Pickem Group Members',
                'db_table': 'pickem_group_members',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickems.gamepickem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pick',
                'verbose_name_plural': 'User Picks',
                'db_table': 'user_picks',
                'unique_together': {('pickem', 'user')},
            },
        ),
    ]
