# Generated by Django 5.2.16 on 2026-07-24 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamELORating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratings_before', models.IntegerField(default=1500)),
                ('ratings_after', models.IntegerField(blank=True, default=1500, null=True)),
                ('gained', models.IntegerField(blank=True, default=0, null=True)),
                ('average_opponent_ratings', models.IntegerField(default=1500)),
                ('highest_ratings', models.IntegerField(default=1500)),
                ('lowest_ratings', models.IntegerField(default=1500)),
                ('average_gain', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': 'Team ELO Rating',
                'verbose_name_plural': 'Team ELO Ratings',
                'db_table': 'team_elo_ratings',
                'ordering': ['-game__week__season__year', 'game__week__week', '-game__game_time', 'team__abbreviation'],
                'unique_together': {('team', 'game')},
            },
        ),
    ]
