# Generated by Django 5.2.16 on 2026-07-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbreviation', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('fullname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(choices=[('NFC East', 'NFC East'), ('NFC North', 'NFC North'), ('NFC South', 'NFC South'), ('NFC West', 'NFC West'), ('AFC East', 'AFC East'), ('AFC North', 'AFC North'), ('AFC South', 'AFC South'), ('AFC West', 'AFC West')], max_length=10)),
                ('color_1', models.CharField(max_length=7)),
                ('color_2', models.CharField(max_length=7)),
                ('color_3', models.CharField(blank=True, max_length=7, null=True)),
                ('color_4', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['abbreviation'],
            },
        ),
    ]
