# Generated by Django 5.2.16 on 2026-07-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_status', models.CharField(choices=[('Out', 'Out'), ('Questionable', 'Questionable'), ('Doubtful', 'Doubtful'), ('Probable', 'Probable')], max_length=20)),
                ('position', models.CharField(max_length=5)),
                ('player_id', models.CharField(max_length=50)),
                ('player_name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_reports', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_injury_reports', to='scheduling.week')),
            ],
            options={
                'verbose_name': 'Team Injury Report',
                'verbose_name_plural': 'Team Injury Reports',
                'db_table': 'team_injury_reports',
                'ordering': ['week', 'team', 'player_name'],
            },
        ),
    ]
