# Generated by Django 5.2.16 on 2026-08-01 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOfTheWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_of_the_week', to='scheduling.game')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_of_the_week', to='scheduling.week')),
            ],
            options={
                'verbose_name': 'Game of the Week',
                'verbose_name_plural': 'Games of the Week',
                'db_table': 'game_of_the_week',
                'ordering': ['-week__season__year', '-week__week', 'game__game_time'],
                'unique_together': {('week', 'game')},
            },
        ),
    ]
