# Generated by Django 5.2.16 on 2026-07-24 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('model_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=5)),
                ('features', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Prediction Model',
                'verbose_name_plural': 'Prediction Models',
                'db_table': 'prediction_models',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_win', models.BooleanField()),
                ('home_win_probability', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.game')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.predictionmodel')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'db_table': 'predictions',
            },
        ),
    ]
