# Team Constants
INACTIVE_TEAMS = ["OAK", "STL", "SD", "LAR"]

# Season Types Constants
REGULAR_SEASON_TYPES = ["REG"]
PLAYOFFS_SEASON_TYPES = ["WC", "DIV", "CON", "SB"]

# Historical Year Constants
HISTORICAL_START_YEAR = 2020
HISTORICAL_END_YEAR = 2025

# ELO Ratings Constants
INITIAL_ELO = 1500
K_FACTOR = 30
HOME_FIELD_ADVANTAGE = 25

# Min/Max Constraints
MIN_SEASON_YEAR = 2020
MAX_SEASON_YEAR = 9999
MIN_WEEK_NUMBER = 1
MAX_WEEK_NUMBER = 99

DEFAULT_SEASON = 2025
DEFAULT_WEEK = 22