# Generated by Django 5.2.16 on 2026-07-24 06:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rushing_attempts', models.IntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('passing_attempts', models.IntegerField(default=0)),
                ('completed_passes', models.IntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('rushing_touchdowns', models.IntegerField(default=0)),
                ('passing_touchdowns', models.IntegerField(default=0)),
                ('sacks_allowed', models.IntegerField(default=0)),
                ('interceptions_thrown', models.IntegerField(default=0)),
                ('fumbles_lost', models.IntegerField(default=0)),
                ('total_epa_gained', models.DecimalField(decimal_places=12, default=Decimal('0.0'), max_digits=15)),
                ('successful_plays', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_stats', to='scheduling.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_stats', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Game Stat',
                'verbose_name_plural': 'Team Game Stats',
                'db_table': 'team_game_stats',
                'ordering': ['-game__week__season__year', 'game__week__week', 'game__game_time'],
                'unique_together': {('game', 'team')},
            },
        ),
    ]
