# Generated by Django 5.2.16 on 2026-07-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0002_teaminjuryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_team', to='teams.team'),
        ),
    ]
