# Generated by Django 5.2.16 on 2026-07-24 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStandings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('home_wins', models.IntegerField(default=0)),
                ('home_losses', models.IntegerField(default=0)),
                ('home_ties', models.IntegerField(default=0)),
                ('away_wins', models.IntegerField(default=0)),
                ('away_losses', models.IntegerField(default=0)),
                ('away_ties', models.IntegerField(default=0)),
                ('conference_wins', models.IntegerField(default=0)),
                ('conference_losses', models.IntegerField(default=0)),
                ('conference_ties', models.IntegerField(default=0)),
                ('division_wins', models.IntegerField(default=0)),
                ('division_losses', models.IntegerField(default=0)),
                ('division_ties', models.IntegerField(default=0)),
                ('point_differential', models.IntegerField(default=0)),
                ('streak', models.CharField(default='-', max_length=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='scheduling.week')),
            ],
            options={
                'verbose_name': 'Team Standings',
                'verbose_name_plural': 'Team Standings',
                'db_table': 'team_standings',
                'ordering': ['-week__season__year', '-week__week', '-percentage', '-wins', 'losses', '-point_differential'],
                'unique_together': {('team', 'week')},
            },
        ),
    ]
