# Generated by Django 5.2.16 on 2026-07-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstandings',
            name='away_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='away_ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='away_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='conference_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='conference_ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='conference_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='division_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='division_ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='division_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='home_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='home_ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='home_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstandings',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
