# Generated by Django 5.2.16 on 2026-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_alter_teamstandings_away_losses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstandings',
            options={'ordering': ['-week__season__year', '-week__week', '-wins', 'losses'], 'verbose_name': 'Team Standings', 'verbose_name_plural': 'Team Standings'},
        ),
        migrations.RemoveField(
            model_name='teamstandings',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='teamstandings',
            name='point_differential',
        ),
        migrations.AddField(
            model_name='teamstandings',
            name='points_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstandings',
            name='points_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
