# Generated by Django 5.2.16 on 2026-07-24 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('season_type', models.CharField(choices=[('Regular', 'Regular'), ('Playoffs', 'Playoffs')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'seasons',
                'ordering': ['-year', 'season_type'],
                'unique_together': {('year', 'season_type')},
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='scheduling.season')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
                'db_table': 'weeks',
                'ordering': ['-season__year', 'week'],
                'unique_together': {('season', 'week')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('game_time', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('home_rest_days', models.PositiveIntegerField(blank=True, null=True)),
                ('away_rest_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Postponed', 'Postponed')], default='Scheduled', max_length=15)),
                ('location', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Neutral', 'Neutral')], default='Neutral', max_length=15)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='scheduling.week')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['-week__season__year', 'week__week', 'game_time'],
                'unique_together': {('week', 'home_team', 'away_team')},
            },
        ),
    ]
